//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoRD.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Claim
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Claim()
        {
            this.Claim_services = new HashSet<Claim_services>();
            this.Claim_status = new HashSet<Claim_status>();
        }
    
        public long claim_number { get; set; }
        public Nullable<System.Guid> user_id { get; set; }
        public Nullable<int> facility_id { get; set; }
        public Nullable<System.DateTime> date_claim { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Claim_services> Claim_services { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Claim_status> Claim_status { get; set; }
        public virtual Facility Facility { get; set; }
        public virtual User User { get; set; }
    }
}
