//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoRD.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Claim_status
    {
        public string status { get; set; }
        public Nullable<System.DateTime> status_date { get; set; }
        public long claim_number { get; set; }
        public System.Guid index_status { get; set; }
    
        public virtual Claim Claim { get; set; }
    }
}
