//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoRD.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Claim_services
    {
        public long claim_number { get; set; }
        public string service_details_text { get; set; }
        public Nullable<System.DateTime> date_visited { get; set; }
        public decimal amount_billed { get; set; }
        public decimal plan_paid { get; set; }
        public decimal plan_discount { get; set; }
        public decimal patient_responsibility { get; set; }
        public System.Guid index_services { get; set; }
    
        public virtual Claim Claim { get; set; }
    }
}
